version: '3.8'

services:
  app:
    image: dictionary-bot
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${SPRING_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${SPRING_DATABASE}
      - MYSQL_USER=${SPRING_DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=localhost
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: